/**
 * Screenshot dimensions, read from the preview image once it loads
 */
export type ImageMeta = {
    width: number
    height: number
    aspectRatio: string
}

/**
 * Response from the moderateImageUrl callable Cloud Function
 */
export type ModerationResult = {
    status: 'ok' | 'warning' | 'error'
    message: string
    verdict?: 'passed' | 'rejected'
    detections?: {
        adult: string
        racy: string
        violence: string
    }
}

export type ProductType =
    // Poster
    | 'PO'
    // Canvas
    | 'S'
    // Framed Print
    | 'FP'
    // Default
    | null

export type ProductFrame =
    // Canvas
    | '075DW'
    | '150DW'
    // Canvas & Framed Print
    | 'BF'
    | 'WF'
    // Framed Print
    | 'EF'
    // Default
    | null

export type ProductEdge =
    // Canvas
    | 'WB'
    | 'BB'
    // Framed Print
    | 'NOMA'
    | '250MA'
    // Default
    | null

/**
 * A region we sell to. Each has one currency and one country Prodigi's costs
 * are quoted for (see regions in src/assets/data/pricing.ts).
 */
export type Region = 'gb' | 'eu' | 'us'

export type Currency = 'GBP' | 'EUR' | 'USD'

/**
 * Prodigi's shipping methods
 */
export type ShippingMethod =
    'Budget' | 'Standard' | 'StandardPlus' | 'Express' | 'Overnight'

/**
 * A product type we sell, e.g. framed print: its Prodigi SKU family, the
 * sizes we offer and its margins (see src/assets/data/pricing.ts)
 */
export type ProductTypeConfig = {
    name: string
    /** SKU family; a size is appended, e.g. GLOBAL-CFP → GLOBAL-CFP-14X24 */
    prodigiSku: string
    /** Sizes in inches ('14x24'), optionally limited to some regions */
    sizes: { size: string; regions?: Region[] }[]
    /** Target gross margin on the product price (0.4 = 40%) */
    margin: number
    /** Lowest margin checkout accepts against Prodigi's live quote */
    minMargin: number
}

/**
 * Prodigi's cost for a catalogue item in one region, including its tax
 */
export type CatalogueCost = {
    itemCost: number
    shipping: Partial<Record<ShippingMethod, number>>
    /** Country of the lab that makes it, e.g. NL for EU orders */
    madeIn: string
}

/**
 * One product size from Prodigi, generated by scripts/prodigi-catalogue.ts
 */
export type CatalogueItem = {
    sku: string
    size: string
    description: string
    /** Pixels Prodigi asks for (300 DPI), for the resolution rating */
    printArea: { width: number; height: number }
    /** Customer choices, e.g. { color: ['black', 'white'] } */
    options: Record<string, string[]>
    costs: Partial<Record<Region, CatalogueCost>>
}

export type Catalogue = {
    generatedAt: string
    products: Record<string, CatalogueItem[]>
}
