/**
 * Generated by scripts/prodigi-catalogue.ts (`yarn catalogue`). Don't edit.
 */
import type { Catalogue } from '@/types'

export const catalogue: Catalogue = {
    generatedAt: '2026-10-02',
    products: {
        'art-print': [
            {
                sku: 'GLOBAL-FAP-14X24',
                size: '14x24',
                description:
                    'EMA, Enhanced Matte Art Paper, 200gsm, 35.56x60.96cm / 14x24"',
                printArea: { width: 4200, height: 7200 },
                options: {},
                costs: {
                    gb: {
                        itemCost: 12,
                        shipping: { Standard: 7.08, Express: 8.4 },
                        madeIn: 'GB'
                    },
                    eu: {
                        itemCost: 12,
                        shipping: { Standard: 8.1, Express: 12.3 },
                        madeIn: 'NL'
                    },
                    us: {
                        itemCost: 15,
                        shipping: { Standard: 12.95, Express: 23.75 },
                        madeIn: 'US'
                    }
                }
            },
            {
                sku: 'GLOBAL-FAP-20X36',
                size: '20x36',
                description:
                    'EMA, Enhanced Matte Art Paper, 200gsm, 50.8x91.44cm / 20x36"',
                printArea: { width: 6000, height: 10800 },
                options: {},
                costs: {
                    gb: {
                        itemCost: 15.6,
                        shipping: { Standard: 7.08, Express: 7.08 },
                        madeIn: 'GB'
                    },
                    eu: {
                        itemCost: 16.8,
                        shipping: { Standard: 12.3, Express: 12.3 },
                        madeIn: 'NL'
                    },
                    us: {
                        itemCost: 20,
                        shipping: { Standard: 15.9, Express: 25.35 },
                        madeIn: 'US'
                    }
                }
            },
            {
                sku: 'GLOBAL-FAP-24X40',
                size: '24x40',
                description:
                    'EMA, Enhanced Matte Art Paper, 200gsm, 60x100cm / 24x40"',
                printArea: { width: 7200, height: 12000 },
                options: {},
                costs: {
                    gb: {
                        itemCost: 21.6,
                        shipping: { Standard: 7.08, Express: 7.08 },
                        madeIn: 'GB'
                    },
                    eu: {
                        itemCost: 21.6,
                        shipping: { Standard: 12.3, Express: 12.3 },
                        madeIn: 'NL'
                    },
                    us: {
                        itemCost: 22,
                        shipping: { Standard: 15.9, Express: 25.35 },
                        madeIn: 'US'
                    }
                }
            }
        ],
        canvas: [
            {
                sku: 'GLOBAL-CAN-14X24',
                size: '14x24',
                description:
                    'Stretched Canvas on a 38mm Standard Stretcher Bar, 14x24" / 36x61cm',
                printArea: { width: 4254, height: 7254 },
                options: {
                    wrap: ['Black', 'ImageWrap', 'MirrorWrap', 'White']
                },
                costs: {
                    gb: {
                        itemCost: 33.6,
                        shipping: { Standard: 12.9, Express: 12.9 },
                        madeIn: 'GB'
                    },
                    eu: {
                        itemCost: 35.7,
                        shipping: { Standard: 11.47, Express: 15.41 },
                        madeIn: 'NL'
                    },
                    us: {
                        itemCost: 38,
                        shipping: { Standard: 25.9, Express: 43.15 },
                        madeIn: 'US'
                    }
                }
            },
            {
                sku: 'GLOBAL-CAN-28X48',
                size: '28x48',
                description:
                    'Stretched Canvas on a 38mm Standard Stretcher Bar, 28x48" / 71x122cm',
                printArea: { width: 8445, height: 14445 },
                options: {
                    wrap: ['Black', 'ImageWrap', 'MirrorWrap', 'White']
                },
                costs: {
                    gb: {
                        itemCost: 72,
                        shipping: { Standard: 31.74, Express: 31.74 },
                        madeIn: 'GB'
                    }
                }
            }
        ],
        'framed-print': [
            {
                sku: 'GLOBAL-CFP-14X24',
                size: '14x24',
                description:
                    'Classic Frame, EMA 200gsm Fine Art Print, No Mount / No Mat, Perspex Glaze, 35x60cm/14x24"',
                printArea: { width: 4200, height: 7200 },
                options: {
                    color: [
                        'black',
                        'brown',
                        'dark grey',
                        'gold',
                        'light grey',
                        'natural',
                        'silver',
                        'white'
                    ]
                },
                costs: {
                    gb: {
                        itemCost: 43.2,
                        shipping: { Standard: 12.9, Express: 12.9 },
                        madeIn: 'GB'
                    },
                    eu: {
                        itemCost: 47.6,
                        shipping: { Standard: 11.47, Express: 15.41 },
                        madeIn: 'NL'
                    },
                    us: {
                        itemCost: 50,
                        shipping: { Standard: 25.9, Express: 43.15 },
                        madeIn: 'US'
                    }
                }
            },
            {
                sku: 'GLOBAL-CFP-20X36',
                size: '20x36',
                description:
                    'Classic Frame, EMA 200gsm Fine Art Print, No Mount / No Mat, Perspex Glaze, 50x91cm/20x36"',
                printArea: { width: 6000, height: 10800 },
                options: {
                    color: [
                        'black',
                        'brown',
                        'dark grey',
                        'gold',
                        'light grey',
                        'natural',
                        'silver',
                        'white'
                    ]
                },
                costs: {
                    gb: {
                        itemCost: 60,
                        shipping: { Standard: 16.86, Express: 16.86 },
                        madeIn: 'GB'
                    },
                    eu: {
                        itemCost: 67.83,
                        shipping: { Standard: 15.41, Express: 15.41 },
                        madeIn: 'NL'
                    },
                    us: {
                        itemCost: 70,
                        shipping: { Standard: 34.55, Express: 74.5 },
                        madeIn: 'US'
                    }
                }
            },
            {
                sku: 'GLOBAL-CFP-22X40',
                size: '22x40',
                description:
                    'Classic Frame, EMA 200gsm Fine Art Print, No Mount / No Mat, Perspex Glaze, 55.88x101.6cm/22x40"',
                printArea: { width: 6600, height: 12000 },
                options: {
                    color: [
                        'black',
                        'brown',
                        'dark grey',
                        'gold',
                        'light grey',
                        'natural',
                        'silver',
                        'white'
                    ]
                },
                costs: {
                    gb: {
                        itemCost: 72,
                        shipping: { Standard: 22.44, Express: 22.62 },
                        madeIn: 'GB'
                    },
                    eu: {
                        itemCost: 78.54,
                        shipping: { Standard: 15.41, Express: 15.41 },
                        madeIn: 'NL'
                    },
                    us: {
                        itemCost: 80,
                        shipping: { Standard: 50.75, Express: 102.55 },
                        madeIn: 'US'
                    }
                }
            }
        ],
        'framed-canvas': [
            {
                sku: 'GLOBAL-FRA-CAN-20X36',
                size: '20x36',
                description:
                    'Global float framed canvas on premium stretcher bars, 20x36" / 51x91 cm',
                printArea: { width: 7200, height: 12000 },
                options: {
                    color: ['black', 'gold', 'natural', 'silver', 'white'],
                    wrap: ['Black', 'ImageWrap', 'MirrorWrap', 'White']
                },
                costs: {
                    gb: {
                        itemCost: 84,
                        shipping: { Standard: 16.86, Express: 16.86 },
                        madeIn: 'GB'
                    },
                    eu: {
                        itemCost: 105.6,
                        shipping: { Standard: 15.54, Express: 15.54 },
                        madeIn: 'NL'
                    },
                    us: {
                        itemCost: 90,
                        shipping: { Standard: 34.55, Express: 74.5 },
                        madeIn: 'US'
                    }
                }
            },
            {
                sku: 'GLOBAL-FRA-CAN-22X40',
                size: '22x40',
                description:
                    'Global float framed canvas on premium stretcher bars, 22x40" / 56x102 cm',
                printArea: { width: 6654, height: 12054 },
                options: {
                    color: ['black', 'gold', 'natural', 'silver', 'white'],
                    wrap: ['Black', 'ImageWrap', 'MirrorWrap', 'White']
                },
                costs: {
                    gb: {
                        itemCost: 93.6,
                        shipping: { Standard: 22.44, Express: 22.62 },
                        madeIn: 'GB'
                    },
                    eu: {
                        itemCost: 126,
                        shipping: { Standard: 15.54, Express: 15.54 },
                        madeIn: 'NL'
                    },
                    us: {
                        itemCost: 105,
                        shipping: { Standard: 50.75, Express: 102.55 },
                        madeIn: 'US'
                    }
                }
            }
        ]
    }
}
