import type {
    Currency,
    ProductTypeConfig,
    Region,
    ShippingMethod
} from '@/types'

/**
 * Pricing config. Edit by hand.
 *
 * Retail prices are worked out from Prodigi's costs (src/assets/data/
 * catalogue.ts, generated by `yarn catalogue`) and these settings, by
 * src/lib/pricing.ts. Re-run `yarn catalogue` after changing the products or
 * sizes here.
 */

/**
 * Regions we sell to. Costs are quoted for one country per region.
 */
export const regions = {
    gb: { name: 'United Kingdom', currency: 'GBP', quoteCountry: 'GB' },
    eu: { name: 'European Union', currency: 'EUR', quoteCountry: 'DE' },
    us: { name: 'United States', currency: 'USD', quoteCountry: 'US' }
} satisfies Record<
    Region,
    { name: string; currency: Currency; quoteCountry: string }
>

/**
 * Product types, their sizes and margins. margin is the margin on the
 * product price after Prodigi's cost and Stripe's card fees (0.4 = 40 of
 * every 100 is profit); minMargin is the floor checkout enforces against
 * Prodigi's live quote.
 */
export const productTypes = {
    'art-print': {
        name: 'Art print',
        prodigiSku: 'GLOBAL-FAP',
        sizes: [{ size: '14x24' }, { size: '20x36' }, { size: '24x40' }],
        margin: 0.6,
        minMargin: 0.25
    },
    canvas: {
        name: 'Canvas',
        prodigiSku: 'GLOBAL-CAN',
        sizes: [{ size: '14x24' }, { size: '28x48' }],
        margin: 0.4,
        minMargin: 0.2
    },
    'framed-print': {
        name: 'Framed print',
        prodigiSku: 'GLOBAL-CFP',
        sizes: [{ size: '14x24' }, { size: '20x36' }, { size: '22x40' }],
        margin: 0.4,
        minMargin: 0.2
    },
    'framed-canvas': {
        name: 'Framed canvas',
        prodigiSku: 'GLOBAL-FRA-CAN',
        sizes: [{ size: '20x36' }, { size: '22x40' }],
        margin: 0.35,
        minMargin: 0.2
    }
} satisfies Record<string, ProductTypeConfig>

export type ProductTypeId = keyof typeof productTypes

/**
 * Prices are rounded up to the next one ending in 4 or 9 (£34, £59)
 */
export const priceStep = 5

/**
 * Shipping is charged at Prodigi's cost (incl. its tax) plus the card fee
 * on it, rounded up
 */
export const shipping: { methods: ShippingMethod[]; roundUpTo: number } = {
    methods: ['Standard', 'Express'],
    roundUpTo: 0.5
}

/**
 * Stripe's card fees, assuming customers pay with a card from their region:
 * UK cards 1.5%, EEA cards 2.5% and other cards 3.25%, plus 2% to convert
 * EUR and USD to GBP, and a fixed 20p (in the region's currency, rounded
 * up). Prices and shipping include them, so margins are after fees.
 */
export const cardFees = {
    gb: { percent: 0.015, fixed: 0.2 },
    eu: { percent: 0.045, fixed: 0.25 },
    us: { percent: 0.0525, fixed: 0.3 }
} satisfies Record<Region, { percent: number; fixed: number }>

/**
 * US quotes exclude sales tax, so allow for it in US prices
 */
export const usSalesTaxBuffer = 0.08

/**
 * Hand-set prices that replace the worked-out ones, by SKU and currency,
 * e.g. { 'GLOBAL-FAP-14X24': { GBP: 29 } }
 */
export const overrides: Record<string, Partial<Record<Currency, number>>> = {}
